
#This is an inverse trigger for the Warp Tools CI workflow. A workaround because otherwise we'll have to remove it as being required for a PR. 
#Currently there is no way to tell Github actions to only make a workflow required for a PR if it actually was triggered by the PR
#More info here: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/troubleshooting-required-status-checks#handling-skipped-but-required-checks
name: Warp Tools CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "develop" and "master" branch
  # Uncomment this block and add your branch name to test without creating a PR
  #push:
    #branches: [ "kp_github_actions_pd-2113" ] 
    #paths-ignore:
    #  - '**/README.md'
  pull_request:
    branches: [ "develop", "master" ]
    paths-ignore:
      - 'tools/**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # The job that builds our container
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
    - run: 'echo "No build required"'
    